package com.demo.entities;
// Generated Apr 26, 2024, 6:17:41 PM by Hibernate Tools 4.3.6.Final

import java.util.Date;
import jakarta.persistence.*;

/**
 * ApplicationHistory generated by hbm2java
 */
@Entity
@Table(name = "application_history", catalog = "vietnamjobs")
public class ApplicationHistory implements java.io.Serializable {

	private Integer id;
	private Postings postings;
	private Seeker seeker;
	private Date created;
	private int status;
	private int result;

	public ApplicationHistory() {
	}

	public ApplicationHistory(Postings postings, Seeker seeker, Date created, int status, int result) {
		this.postings = postings;
		this.seeker = seeker;
		this.created = created;
		this.status = status;
		this.result = result;
	}

	@Id
	@GeneratedValue(strategy = GenerationType.IDENTITY)

	@Column(name = "id", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "postings_id", nullable = false)
	public Postings getPostings() {
		return this.postings;
	}

	public void setPostings(Postings postings) {
		this.postings = postings;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "seeker_id", nullable = false)
	public Seeker getSeeker() {
		return this.seeker;
	}

	public void setSeeker(Seeker seeker) {
		this.seeker = seeker;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "created", nullable = false, length = 10)
	public Date getCreated() {
		return this.created;
	}

	public void setCreated(Date created) {
		this.created = created;
	}

	@Column(name = "status", nullable = false)
	public int getStatus() {
		return this.status;
	}

	public void setStatus(int status) {
		this.status = status;
	}

	@Column(name = "result", nullable = false)
	public int getResult() {
		return this.result;
	}

	public void setResult(int result) {
		this.result = result;
	}

}
