package com.demo.entities;
// Generated Apr 26, 2024, 6:17:41 PM by Hibernate Tools 4.3.6.Final

import java.util.HashSet;
import java.util.Set;
import jakarta.persistence.*;

/**
 * Category generated by hbm2java
 */
@Entity
@Table(name = "category", catalog = "vietnamjobs")
public class Category implements java.io.Serializable {

	private Integer id;
	private int name;
	private int categoryParent;
	private Set<Postings> postingses = new HashSet<Postings>(0);
	private Set<Keyword> keywords = new HashSet<Keyword>(0);

	public Category() {
	}

	public Category(int name, int categoryParent) {
		this.name = name;
		this.categoryParent = categoryParent;
	}

	public Category(int name, int categoryParent, Set<Postings> postingses, Set<Keyword> keywords) {
		this.name = name;
		this.categoryParent = categoryParent;
		this.postingses = postingses;
		this.keywords = keywords;
	}

	@Id
	@GeneratedValue(strategy = GenerationType.IDENTITY)
	@Column(name = "id", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@Column(name = "name", nullable = false)
	public int getName() {
		return this.name;
	}

	public void setName(int name) {
		this.name = name;
	}

	@Column(name = "category_parent", nullable = false)
	public int getCategoryParent() {
		return this.categoryParent;
	}

	public void setCategoryParent(int categoryParent) {
		this.categoryParent = categoryParent;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "category")
	public Set<Postings> getPostingses() {
		return this.postingses;
	}

	public void setPostingses(Set<Postings> postingses) {
		this.postingses = postingses;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "category")
	public Set<Keyword> getKeywords() {
		return this.keywords;
	}

	public void setKeywords(Set<Keyword> keywords) {
		this.keywords = keywords;
	}

}
