package com.demo.entities;
// Generated Apr 26, 2024, 6:17:41 PM by Hibernate Tools 4.3.6.Final

import java.util.HashSet;
import java.util.Set;
import jakarta.persistence.*;

/**
 * Employer generated by hbm2java
 */
@Entity
@Table(name = "employer", catalog = "vietnamjobs")
public class Employer implements java.io.Serializable {

	private Integer id;
	private Account account;
	private String name;
	private String scale;
	private String logo;
	private String link;
	private String description;
	private String address;
	private String mapLink;
	private boolean status;
	private Set<Follow> follows = new HashSet<Follow>(0);
	private Set<Postings> postingses = new HashSet<Postings>(0);

	public Employer() {
	}

	public Employer(Account account, String name, String scale, String logo, String link, String description,
			String address, String mapLink, boolean status) {
		this.account = account;
		this.name = name;
		this.scale = scale;
		this.logo = logo;
		this.link = link;
		this.description = description;
		this.address = address;
		this.mapLink = mapLink;
		this.status = status;
	}

	public Employer(Account account, String name, String scale, String logo, String link, String description,
			String address, String mapLink, boolean status, Set<Follow> follows, Set<Postings> postingses) {
		this.account = account;
		this.name = name;
		this.scale = scale;
		this.logo = logo;
		this.link = link;
		this.description = description;
		this.address = address;
		this.mapLink = mapLink;
		this.status = status;
		this.follows = follows;
		this.postingses = postingses;
	}

	@Id
	@GeneratedValue(strategy = GenerationType.IDENTITY)

	@Column(name = "id", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "account_id", nullable = false)
	public Account getaccount() {
		return this.account;
	}

	public void setaccount(Account account) {
		this.account = account;
	}

	@Column(name = "name", nullable = false, length = 400)
	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	@Column(name = "scale", nullable = false, length = 300)
	public String getScale() {
		return this.scale;
	}

	public void setScale(String scale) {
		this.scale = scale;
	}

	@Column(name = "logo", nullable = false, length = 250)
	public String getLogo() {
		return this.logo;
	}

	public void setLogo(String logo) {
		this.logo = logo;
	}

	@Column(name = "link", nullable = false, length = 400)
	public String getLink() {
		return this.link;
	}

	public void setLink(String link) {
		this.link = link;
	}

	@Column(name = "description", nullable = false, length = 65535)
	public String getDescription() {
		return this.description;
	}

	public void setDescription(String description) {
		this.description = description;
	}

	@Column(name = "address", nullable = false, length = 65535)
	public String getAddress() {
		return this.address;
	}

	public void setAddress(String address) {
		this.address = address;
	}

	@Column(name = "map_link", nullable = false, length = 65535)
	public String getMapLink() {
		return this.mapLink;
	}

	public void setMapLink(String mapLink) {
		this.mapLink = mapLink;
	}

	@Column(name = "status", nullable = false)
	public boolean isStatus() {
		return this.status;
	}

	public void setStatus(boolean status) {
		this.status = status;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "employer")
	public Set<Follow> getFollows() {
		return this.follows;
	}

	public void setFollows(Set<Follow> follows) {
		this.follows = follows;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "employer")
	public Set<Postings> getPostingses() {
		return this.postingses;
	}

	public void setPostingses(Set<Postings> postingses) {
		this.postingses = postingses;
	}

}
