package com.demo.entities;
// Generated Apr 26, 2024, 6:17:41 PM by Hibernate Tools 4.3.6.Final

import java.util.HashSet;
import java.util.Set;
import jakarta.persistence.*;

/**
 * Seeker generated by hbm2java
 */
@Entity
@Table(name = "seeker", catalog = "vietnamjobs")
public class Seeker implements java.io.Serializable {

	private Integer id;
	private Account account;
	private String fullname;
	private String phone;
	private String description;
	private String cvInformation;
	private boolean status;
	private Set<ApplicationHistory> applicationHistories = new HashSet<ApplicationHistory>(0);
	private Set<Follow> follows = new HashSet<Follow>(0);
	private Set<CheckNews> checkNewses = new HashSet<CheckNews>(0);

	public Seeker() {
	}

	public Seeker(Account account, String fullname, String phone, String description, String cvInformation,
			boolean status) {
		this.account = account;
		this.fullname = fullname;
		this.phone = phone;
		this.description = description;
		this.cvInformation = cvInformation;
		this.status = status;
	}

	public Seeker(Account account, String fullname, String phone, String description, String cvInformation,
			boolean status, Set<ApplicationHistory> applicationHistories, Set<Follow> follows,
			Set<CheckNews> checkNewses) {
		this.account = account;
		this.fullname = fullname;
		this.phone = phone;
		this.description = description;
		this.cvInformation = cvInformation;
		this.status = status;
		this.applicationHistories = applicationHistories;
		this.follows = follows;
		this.checkNewses = checkNewses;
	}

	@Id
	@GeneratedValue(strategy = GenerationType.IDENTITY)
	@Column(name = "id", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "account_id", nullable = false)
	public Account getaccount() {
		return this.account;
	}

	public void setaccount(Account account) {
		this.account = account;
	}

	@Column(name = "fullname", nullable = false, length = 250)
	public String getFullname() {
		return this.fullname;
	}

	public void setFullname(String fullname) {
		this.fullname = fullname;
	}

	@Column(name = "phone", nullable = false, length = 250)
	public String getPhone() {
		return this.phone;
	}

	public void setPhone(String phone) {
		this.phone = phone;
	}

	@Column(name = "description", nullable = false, length = 65535)
	public String getDescription() {
		return this.description;
	}

	public void setDescription(String description) {
		this.description = description;
	}

	@Column(name = "cv_information", nullable = false, length = 250)
	public String getCvInformation() {
		return this.cvInformation;
	}

	public void setCvInformation(String cvInformation) {
		this.cvInformation = cvInformation;
	}

	@Column(name = "status", nullable = false)
	public boolean isStatus() {
		return this.status;
	}

	public void setStatus(boolean status) {
		this.status = status;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "seeker")
	public Set<ApplicationHistory> getApplicationHistories() {
		return this.applicationHistories;
	}

	public void setApplicationHistories(Set<ApplicationHistory> applicationHistories) {
		this.applicationHistories = applicationHistories;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "seeker")
	public Set<Follow> getFollows() {
		return this.follows;
	}

	public void setFollows(Set<Follow> follows) {
		this.follows = follows;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "seeker")
	public Set<CheckNews> getCheckNewses() {
		return this.checkNewses;
	}

	public void setCheckNewses(Set<CheckNews> checkNewses) {
		this.checkNewses = checkNewses;
	}

}
