package com.demo.entities;
// Generated Apr 26, 2024, 6:17:41 PM by Hibernate Tools 4.3.6.Final

import java.util.Date;
import jakarta.persistence.*;

/**
 * TransactionHistory generated by hbm2java
 */
@Entity
@Table(name = "transaction_history", catalog = "vietnamjobs")
public class TransactionHistory implements java.io.Serializable {

	private Integer id;
	private Account account;
	private double total;
	private Date created;
	private int tradingCode;

	public TransactionHistory() {
	}

	public TransactionHistory(Account account, double total, Date created, int tradingCode) {
		this.account = account;
		this.total = total;
		this.created = created;
		this.tradingCode = tradingCode;
	}

	@Id
	@GeneratedValue(strategy = GenerationType.IDENTITY)

	@Column(name = "id", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "account_id", nullable = false)
	public Account getaccount() {
		return this.account;
	}

	public void setaccount(Account account) {
		this.account = account;
	}

	@Column(name = "total", nullable = false, precision = 22, scale = 0)
	public double getTotal() {
		return this.total;
	}

	public void setTotal(double total) {
		this.total = total;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "created", nullable = false, length = 10)
	public Date getCreated() {
		return this.created;
	}

	public void setCreated(Date created) {
		this.created = created;
	}

	@Column(name = "trading_code", nullable = false)
	public int getTradingCode() {
		return this.tradingCode;
	}

	public void setTradingCode(int tradingCode) {
		this.tradingCode = tradingCode;
	}

}
