package com.demo.entities;
// Generated Apr 26, 2024, 6:17:41 PM by Hibernate Tools 4.3.6.Final

import java.util.HashSet;
import java.util.Set;
import jakarta.persistence.*;

/**
 * Type generated by hbm2java
 */
@Entity
@Table(name = "type", catalog = "vietnamjobs")
public class Type implements java.io.Serializable {

	private Integer id;
	private String name;
	private Set<Postings> postingses = new HashSet<Postings>(0);

	public Type() {
	}

	public Type(String name) {
		this.name = name;
	}

	public Type(String name, Set<Postings> postingses) {
		this.name = name;
		this.postingses = postingses;
	}

	@Id
	@GeneratedValue(strategy = GenerationType.IDENTITY)

	@Column(name = "id", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@Column(name = "name", nullable = false, length = 250)
	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "type")
	public Set<Postings> getPostingses() {
		return this.postingses;
	}

	public void setPostingses(Set<Postings> postingses) {
		this.postingses = postingses;
	}

}
